#cloud-config
packages:
  - nfs-kernel-server
  - curl
  - wget
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - nfs-common
  - open-iscsi
  - lsscsi
  - sg3-utils
  - multipath-tools
  - scsitools
write_files:
  - content: |
      defaults {
          user_friendly_names yes
          find_multipaths yes
      }
    path: /etc/multipath.conf
    append: true
runcmd:
  - mkdir -p /mnt/sharedfolder
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt install -y docker-ce docker-ce-cli containerd.io
  - usermod -aG docker ubuntu
  - service open-iscsi start
  - service multipath-tools start
  - nc -l 1234 # signal local-exec provisioner that cloud-init cmds are complete
  
