apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pnnlmiscscripts.pixiecore.simpleconfig.fullname" . }}
  labels:
    app: {{ template "pnnlmiscscripts.pixiecore.simpleconfig.name" . }}
    chart: {{ template "pnnlmiscscripts.pixiecore.simpleconfig.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pnnlmiscscripts.pixiecore.simpleconfig.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pnnlmiscscripts.pixiecore.simpleconfig.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/v1/boot
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "pnnlmiscscripts.pixiecore.simpleconfig.fullname" . }}
          items:
{{- range $key, $value := .Values.config }}
          - key: {{ $key | replace ":" "" | quote }}
            path: {{ $key | quote }}
{{- end }}
