---
- name: Install Docker
  hosts: localhost
  connection: local
 
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    
    - name: Install containerd
      dnf:
        name: 'https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm'
        state: present
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
 
    - name: Add user solidfire to docker group
      user:
        name: solidfire
        groups: docker
        append: yes
      become: yes