name: Publish Images
on:
  release:
    types: [published, created, edited, released, prereleased]

jobs:
  publish:
    name: Build and Publish Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(git describe --tags --abbrev=0)
      - name: Build and Publish - Boot
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sgryczan/titania-boot
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          registry: docker.io
          dockerfile: Dockerfile
          tags: "latest,${{ env.RELEASE_VERSION }}"
      - name: Build and Publish - API
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VERSION: ${{ env.RELEASE_VERSION }}"
        with:
          name: sgryczan/titania-api
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          registry: docker.io
          workdir: api/
          dockerfile: Dockerfile
          buildargs: VERSION
          tags: "latest,${{ env.RELEASE_VERSION }}"